[config]

[templates.kitty]
  input_path  = './templates/terminal/kitty.conf'
  output_path = '~/.config/kitty/colors.conf'

# [templates.zshTheme]
#   input_path  = './templates/terminal/zsh_color.zsh'
#   output_path = '~/zsh/themes/color-palette.zsh-theme'
#
# [templates.terminal_colors]
#   input_path  = './templates/terminal/colors.json'
#   output_path = '~/.cache/wal/colors.json'

[templates.hyprland]
  input_path  = './templates/hypr/hyprland.conf'
  output_path = '~/.config/hypr/hyprland/colors.conf'

[templates.waybar]
  input_path  = './templates/waybar-colors.css'
  output_path = '~/.config/waybar/colors.css'

[templates.tmux]
  input_path  = './templates/terminal/tmux_colors.conf'
  output_path = '~/.tmux_colors.conf'

[templates.qtbrowser]
  input_path  = './templates/qtbrowser.py'
  output_path = '~/.config/qutebrowser/themes/palette.py'

[templates.startship]
  input_path  = './templates/terminal/starship-colors.toml'
  output_path = '~/.config/starship/starship.toml'

# [templates.hyprlock-icon]
#   input_path  = './templates/hypr/icon.svg'
#   output_path = '~/.cache/wal/icon.svg'

[templates.btop]
  input_path  = './templates/terminal/btop.theme'
  output_path = '~/.config/btop/themes/matugen.theme'

[templates.bat]
  input_path  = './templates/terminal/bat.tmTheme'
  output_path = '~/.config/bat/themes/Matugen.tmTheme'

[templates.yazi]
  input_path  = './templates/terminal/yazi.toml'
  output_path = '~/.config/yazi/theme.toml'

# [templates.fish]
#   input_path  = './templates/terminal/colors.fish'
#   output_path = '~/.config/fish/themes/Matugen.theme'

# [templates.fzf-fish]
#   input_path  = './templates/terminal/fzf.fish'
#   output_path = '~/.cache/wal/fzf.fish'

[templates.rofi]
  input_path  = './templates/rofi.rasi'
  output_path = '~/.config/rofi/colors.rasi'

# [templates.qtct]
#   input_path  = './templates/qtct.conf'
#   output_path = '~/.local/share/color-schemes/Matugen.colors'

# [templates.fzfh]
#   input_path  = './templates/terminal/fzf_syntax_high.zsh'
#   output_path = '~/zsh/themes/fzf_syntax_high.zsh'

# [templates.zshcolor]
#   input_path  = './templates/terminal/zsh_color.zsh'
#   output_path = '~/zsh/themes/color-palette.zsh-theme'
#
# [templates.ls]
#   input_path  = './templates/terminal/ls_color.zsh'
#   output_path = '~/zsh/themes/ls_color.zsh'
#
# [templates.fzf]
#   input_path  = './templates/terminal/fzf.zsh'
#   output_path = '~/zsh/themes/fzf_theme.zsh'

# [templates.gtk4]
#   input_path  = './templates/gtk/colors.css'
#   output_path = '~/.config/gtk-4.0/gtk.css'
#
# [templates.gtk3]
#   input_path  = './templates/gtk/colors.css'
#   output_path = '~/.config/gtk-3.0/gtk.css'

# [templates.folders-color]
#   input_path  = './templates/folder-color.txt'
#   output_path = '~/.cache/wal/folder-color.txt'

# [templates.spicetify]
#   input_path  = './templates/spotify.ini'
#   output_path = '~/.config/spicetify/Themes/marketplace/color.ini'

[templates.neovim-nvchad]
  input_path  = './templates/terminal/nvchad.lua'
  output_path = '~/.local/share/nvim/lazy/base46/lua/base46/themes/matugen.lua'

# [templates.vesktop]
#   input_path  = "./templates/discord.css"
#   output_path = "~/.config/vesktop/themes/Matugen.css"

[templates.cava]
  input_path  = "./templates/terminal/cava.config"
  output_path = "~/.config/cava/config"

[templates.dgop]
  input_path  = "./templates/dgop.json"
  output_path = "~/.config/dgop/colors.json"

# [templates.dank]
#   input_path  = "./templates/dank.json"
#   output_path = "~/.cache/DankMaterialShell/dms-colors.json"

[templates.nvim]
input_path = '~/.config/nvim/pywal/matugen.lua'
output_path = '~/.cache/wal/base46-dark.lua'

[templates.nvimlight]
input_path = '~/.config/nvim/pywal/matugen.lua'
output_path = '~/.cache/wal/base46-light.lua'

[templates.pywal]
input_path = '~/.config/nvim/pywal/waltemplate'
output_path = '~/.cache/wal/colors'

[config.custom_colors.warning]
  color = "#f9e2af"
  blend = true

[config.custom_colors.info]
  color = "#89b4fa"
  blend = true

[config.custom_colors.success]
  color = "#a6e3a1"
  blend = true

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true
