# Prompt symbols
[character]
success_symbol = "[❯](bold #a1c9fd)"  # Foam color
error_symbol = "[❯](bold #d7bde4)"  # Love color

# Directory Path
[directory]
style = "bold #c3c6cf"  # Text color
read_only = " "
read_only_style = "bold #a1c9fd"  # Gold color

# Git Branch
[git_branch]
symbol = " "
style = "bold #a1c9fd"  # Iris color

# Git Status
[git_status]
style = "bold #a1c9fd"  # Gold
conflicted = "⚔ "
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕"
modified = "*"
staged = "+"
deleted = "✘"
untracked = "?"

# Disable unused modules for minimalism
[package]
disabled = true
